<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Body dimensions -->
<xacro:property name="body_link_x_dim" value="0.5"/>
<xacro:property name="body_link_y_dim" value="0.3"/>
<xacro:property name="body_link_z_dim" value="0.15"/>

<!-- Wheel dimensions -->
<xacro:property name="wheel_link_radius" value="0.075"/>
<xacro:property name="wheel_link_length" value="0.05"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>

<!-- Material density -->
<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<!-- Pi constant -->
<xacro:property name="pi_const" value="3.1415926"/>

<!-- Robot body and wheel mass -->
<xacro:property name="body_mass" 
value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>

<xacro:property name="wheel_mass"
value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>

<!-- Moments of inertia of the wheel -->
<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}"/>

<!-- This macro defines the complete inertial section of the wheel -->
<!-- It is used later in the code -->
<xacro:macro name="inertia_wheel">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>

<!-- Over here we include the file that defines extra Gazebo options and motion control driver -->
<xacro:include filename="$(find four_wheel_bot)/urdf/gazebo_controller.xacro"/>

<!-- FROM HERE WE DEFINE LINKS, JOINTS -->


<link name="odom"/>
<joint name="base_joint" type="fixed">
    <parent link="odom"/>
    <child link="body_link"/>
</joint>

<!-- START: Body link of the robot -->

<link name="body_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    
    <collision>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia 
        ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}"
        ixy="0" ixz="0" iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}"
        iyz="0"
        izz="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}"/>
    </inertial>
</link>

<!-- END: Body link of the robot -->

<!-- START: Back right wheel of the robot and the joint -->
<joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="0.15 -0.175 -0.07" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel1_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>
    
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>
    
    <xacro:inertia_wheel />
</link>

<!-- END: Back right wheel of the robot and the joint -->

<!-- START: Back left wheel of the robot and the joint -->
<joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="0.15 0.175 -0.07" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel2_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>
    
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>
    
    <xacro:inertia_wheel />
</link>

<!-- END: Back left wheel of the robot and the joint -->

<!-- START: Front right wheel of the robot and the joint -->
<joint name="wheel3_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel3_link"/>
    <origin xyz="-0.15 -0.175 -0.07" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel3_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>
    
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>
    
    <xacro:inertia_wheel />
</link>

<!-- END: Front right wheel of the robot and the joint -->

<!-- START: Front left wheel of the robot and the joint -->

<joint name="wheel4_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel4_link"/>
    <origin xyz="-0.15 0.175 -0.07" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel4_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>
    
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>
    
    <xacro:inertia_wheel />
</link>

<!-- END: Front left wheel of the robot and the joint -->

<!-- START: Sensors -->

<!-- Camera sensor link and joint -->
<link name="camera_link">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="0.025 0.025 0.025"/>
        </geometry>
        <material name="Gazebo/Blue"/>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
    </collision>
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
</link>

<joint name="camera_joint" type="fixed">
    <parent link="body_link"/>
    <child link="camera_link"/>
    <origin xyz="0.238 0 0.088" rpy="0 0 0"/>
</joint>

<!-- Optical frame for camera (REP-103 compliant) -->
<joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    
    
</joint>

<link name="camera_link_optical"></link>

<!-- Lidar sensor link and joint -->
<link name="lidar_link">
    <visual>
        <origin rpy="0 0 0" xyz="-0.023 0 0.032"/>
        <geometry>
            <cylinder length="0.03" radius="0.025"/>
        </geometry>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0.3 0 0.25"/>
        <geometry>
            <cylinder length="0.06" radius="0.05"/>
        </geometry>
    </collision>
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
</link>

<joint name="lidar_joint" type="fixed">
    <parent link="body_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.0 0 0.06" rpy="0 0 0.088"/>
</joint>

<!-- Provide a REP-105 style alias frame expected by some tools -->
<link name="laser_frame"/>
<joint name="laser_frame_joint" type="fixed">
    <parent link="lidar_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    
    
</joint>

<!-- Gazebo plugins for sensors -->
<gazebo reference="camera_link">
    <material>Gazebo/Black</material>
    <sensor name="camera" type="camera">
        <pose> 0 0 0 0 0 0 </pose>
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <camera>
            <horizontal_fov>1.089</horizontal_fov>
            <image>
                <format>R8G8B8</format>
                <width>640</width>
                <height>480</height>
            </image>
            <clip>
                <near>0.05</near>
                <far>8.0</far>
            </clip>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <frame_name>camera_link_optical</frame_name>
        </plugin>
    </sensor>
</gazebo>

<gazebo reference="lidar_link">
    <material>Gazebo/Black</material>
    <sensor name="laser" type="ray">
        <pose> 0.06 0 0 0 0 0 </pose>
        <always_on>true</always_on>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <ray>
            <scan>
                <horizontal>
                    <samples>360</samples>
                    <min_angle>-3.14</min_angle>
                    <max_angle>3.14</max_angle>
                </horizontal>
            </scan>
            <range>
                <min>0.3</min>
                <max>12.0</max>
            </range>
        </ray>
        <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
            <ros>
                <argument>~/out:=scan</argument>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>laser_frame</frame_name>
        </plugin>
    </sensor>
</gazebo>

<!-- END: Sensors -->

</robot>